### PR TITLE
Helm charts

### PR DESCRIPTION
**Pull request by orihomie**

### CODE REVIEW

**Comment by orihomie** [comment]
@caarlos0 would you be able for reviewing?

**Comment by caarlos0** [comment]
maybe submit this to helm's community charts? This is not a helm repo, so users can't add it anyway...

**Comment by orihomie** [comment]
I've checked out publishing on artifacthub.io and that seemed to be complicated for me, I'd go [github pages](https://helm.sh/docs/howto/chart_releaser_action/) way on my own repo.

**Comment by caarlos0** [comment]
closing this as previously stated

**Pull request closed without merging**
