### PR TITLE
 Add support is,cz,fr,ie,pl,ca,co.uk domains 

### PR DESCRIPTION
**Pull request by kirun666**
Also in this pull request there are [changes](https://github.com/caarlos0/domain_exporter/commit/41ca2348e3acfbd85cc7e5146cf3624a050ce240#diff-7ddfb3e035b42cd70649cc33393fe32cL87) that relate to the targets specified with www part. 
Whois service does not work with such domains, so I implemented an automatic replacement of such targets domains (www part is skipped).

### CODE REVIEW

**Comment by caarlos0** [comment]
why?

**Comment by kirun666** [comment]
Hello @caarlos0 ! 
If you think that everything is good in my commits - then please accept my pull request.

**Comment by caarlos0** [comment]
can you add some tests?

**Comment by caarlos0** [comment]
also, the commitlint bot is complaining about the commit format.

Please follow `type: message`, as for example, `feat: added support for .io domains`. 

Unfortunately this bot's messages are not very clear :/

**Comment by kirun666** [comment]
Hello @caarlos0 ! I added tests and fix commit message

**Comment by caarlos0** [comment]
thanks

**Pull request merged**
